### ISSUE TITLE
Indexable mixin for middleclass 3.x feature request

### ISSUE THREAD

**Issue by rafis** [kikito/middleclass#24]
I'm porting PHP web framework to Lua. All is going well except I need something to replace PHP getter `__get()`. In previous versions there was Indexable mixin with `index()` function, I need same for middleclass 3.x.

Also question about porting, I'm replacing `get_class($this)` with `self.class.name`, is it proper to get class name in such way? Also question how to call method in parent class, the way present in wiki a bit wierd, if I try `self.class.super.method(self, ...)` it gives wrong parent on second level of inheritence, it gives parent of first level. My temporary solution:

    local Database_Query_Builder_Select = Database_Query_Builder_Where:subclass('Database_Query_Builder_Select')
    local parent = Database_Query_Builder_Where

    function Database_Query_Builder_Select:initialize(columns)
        ...

        -- Start the query with no actual SQL statement
        parent.initialize(self, Database.SELECT)
    end

**Comment by xpol** [comment]
:+1:

**Comment by kikito** [comment]
Hi everyone,

This has taken a while to mature, but I have just published v4.0.0 of middleclass. This version of middleclass comes with a revamped way of doing the method lookup, and this includes support for `__index`. Please check it out!

I am closing this issue now, happy new year!
