### ISSUE TITLE
Documentation for inheritance

### ISSUE THREAD

**Issue by raffomania** [kikito/middleclass#25]
Please close if I missed a part of the docs ;)
I'd like to have some information about inheritance in middle class - the lua users wiki (http://lua-users.org/wiki/ObjectOrientedProgramming) says it supports "basic inheritance". If so, how exactly does it work and what are it's limitations?

**Comment by kikito** [comment]
Hello there,

The documentation that exists is in the Wiki:

https://github.com/kikito/middleclass/wiki

Is this enough for you, or do you need more guidance?

**Comment by raffomania** [comment]
Thanks! I found the documentation in the wiki and read it, but didn't find any information on how inheritance works.

**Comment by kikito** [comment]
I'm afraid I will have to ask you to be more concise. Are you looking for a description of inheritance as a concept in object orientation? Are you asking about the implementation details of that concept in the context of this library? Or is it something else?

**Comment by raffomania** [comment]
I'm looking for precise usage instructions on inheritance in middleclass:
- What is the Syntax for inheritance? From the quick example, my guess would be that 
    class('A', B)
sets up A to be a subclass of B. But it took me a while to find this, maybe it could be explicitly stated somewhere else?
- How is initialization handled in class hierarchies? Is the constructor of parent classes automatically called?
- Is there a way to access a classes or an instances parent class/instance? E.g. A.__super__?

**Comment by kikito** [comment]
The standard way to do inheritance is `class('A', B)`. In addition to that, you can also do `B:subclass('A')`. Both expressions will return A (a subclass of B). `A.super` will return `B`.

When you call A:new(), only `A:initialize()` gets called - the constructor of B is not called by default. There is no `super`, instead you have to use an explicit `self`:

```lua
function A:initialize()
  ...
  B.initialize(self, ...)
  ...
end
```

The same applies for non-constructor methods - there is no `super` keyword-like construction, so you must use explicit self calls.

You may find an example of all this in the [Quick Example](https://github.com/kikito/middleclass/wiki/Quick-Example) and on the [Readme](https://github.com/kikito/middleclass/blob/master/README.md). Do you feel they are not clear enough?

**Comment by raffomania** [comment]
Hey,
that's nice! It clarified a lot of things for me. Indeed, I feel that the Wiki should contain a part exactly like your comment above, to explicitly explain how inheritance works.

**Comment by kikito** [comment]
Added the notes to the Quick intro pages. Closing down this issue.
