### ISSUE TITLE
Comparison metamethods don't seem to work in inherited classes.

### ISSUE THREAD

**Issue by CalinLeafshade** [kikito/middleclass#26]
Consider the following:

Class B inherits Class A
Class C inherits Class A

Class A implements __lt comparison meta method.

When comparing Class B and Class C the library errors with "Trying to compare two tables"

**Comment by kikito** [comment]
Hi there,

I can't reproduce this. Here's the code I used:

``` lua
local class = require 'middleclass'

local A = class('A')
function A:__lt(b) return true end

local B = class('B', A)
local C = class('C', A)

local b, c = B:new(), C:new()

print(b < c) -- prints true, no error
```
I suspect the error might be originating not in middleclass, but in the code that you used to codify the `__lt` function - you might be attempting to compare two tables inside it. I recommend you to check the line which throws the error.

If this is not the case, please provide a failing example.

**Comment by kikito** [comment]
Since there was no response, I am going to close down this issue for now. Please re-open it again if the problem persist.
