### ISSUE TITLE
about aClass.static's metamethod

### ISSUE THREAD

**Issue by yuliying** [kikito/middleclass#27]
could it be bettle if we change
setmetatable(aClass.static, { __index = function(_,k) return dict[k] or superStatic[k] end }) 
to
setmetatable(aClass.static, { __index = function(_,k) return rawget(dict,k) or superStatic[k] end }) 
?

**Comment by kikito** [comment]
Hi, sorry it took me a while to answer to this issue. I have been terribly busy during the last month.

Can you explain a bit why you think this change would be better? If you think it could be faster, can you make a performance test demonstrating it, for example? I ask this because in my experience Lua has some surprising edge cases in performance, where it acts counter intuitively, and this could be one of them.

In any case, thanks for opening an issue, and sorry for the delay in answering! (I should be faster now)

**Comment by yuliying** [comment]
because of __instanceDict 's __index metamethod . 
when we need to search a key from a static table , the searching path is : 
       static[lv0] -> dict[lv0] -> super[lv1] dict -> super[lv2] dict -> super[lv1] static -> super[lv1] dict -> super[lv2] dict ->  super[lv2] static -> super[lv2] dict . 

I'am sorry if i had some misunderstanding  of your code.

**Comment by kikito** [comment]
Hi, can you do an example with real classes and methods? I am not sure I know what lvl0-2 mean in your current one.

**Comment by yuliying** [comment]
for convenient , i add some log to the code:
---------------------------------------------------------
local function _setClassDictionariesMetatables(aClass)
  local dict = aClass.__instanceDict
  --dict.__index = dict
  dict.__index = function(_ , k) print("find [".. k  .. "] from father dict") ;return dict[k] end
  local super = aClass.super
  if super then
    local superStatic = super.static
    setmetatable(dict, super.__instanceDict)
    --setmetatable(aClass.static, { __index = function(_,k) return dict[k] or superStatic[k] end })
        setmetatable(aClass.static, { __index = function(_,k)
                print("find [" .. k ..  "] from self dict")
                --local a = dict[k]
                local a = rawget(dict , k)
                if a then return a end
                print("find [".. k  ..  "] from superStatic")
                return superStatic[k]
        end })
  else
    setmetatable(aClass.static, { __index = function(_,k) return dict[k] end }) end
end
--------------------------test1-------------------------------
local class = require "middleclass"
local A = class("A")
A.static.hello = 1
A.hello = 2
print(A.hello)
     output: 1
     from test 1 , we know that , value in static table has a higher priority .
--------------------------test2-------------------------------
local class = require "middleclass"
local GRANDFATHER = class("GRANDFATHER")
GRANDFATHER.static.hello = 1
local FATHER = class("FATHER" , GRANDFATHER )
local CHILD = class("CHILD" , FATHER)
print("----------------------------------")
print(CHILD.hello)
    output:  
          -- here find from self static first
          find [hello] from self dict
          find [hello] from father dict
          find [hello] from father dict
          find [hello] from father dict
          find [hello] from superStatic 
          find [hello] from self dict
          find [hello] from father dict
          find [hello] from father dict
          find [hello] from superStatic
         1
-----------------------------------------------------
if we change "local a = dict[k]"  to "local a = rawget(dict , k)" , test2's output:
         -- here find from self static first
         find [hello] from self dict
         find [hello] from superStatic
         find [hello] from self dict
         find [hello] from superStatic
        1
----------------------------------------------------
if we use dict[k] , we find k from 
    self static -> self dict -> father dict -> grand father dict -> father static -> father dict -> grand father dict
    -> grand father static -> grand father dict .
   
search father dict too many times.

**Comment by qaisjp** [comment]
Something about parent tables being checked too much

**Comment by kikito** [comment]
I have merged this change. Thanks a lot, @yuliying!
