### ISSUE TITLE
Wiki update about methamethods

### ISSUE THREAD

**Issue by tapir** [kikito/middleclass#36]
On wiki it's said that the full list of supported methamethods are: ```'__add', '__call', '__concat', '__div', '__le', '__lt', '__mod', '__mul', '__pow', '__sub', '__tostring', '__unm' ```
whereas I've had success with ```__eq``` as well. Is this info dated or was it not supposed to work?

Thanks

**Comment by kikito** [comment]
Thanks a lot, I have updated the wiki. The new version of Middleclass supports all metamethods, including `__index`.
