### ISSUE TITLE
Missing documentation for isInstanceOf, isSubclassOf, allocate and subclassed

### ISSUE THREAD

**Issue by MrStradivarius** [kikito/middleclass#38]
This is a very nice library - thank you for your work!

I noticed that in the library there are four default methods that aren't mentioned in the wiki documentation, namely `isInstanceOf`, `isSubclassOf`, `allocate` and `subclassed`. Was there documentation for these that got deleted from the wiki somehow? I see references to `isInstanceOf` and `isSubclassOf` in UPDATING.md, which makes me suspect that there might have been something there before. In any case, it would be nice to have some documentation and examples for these methods.

**Comment by kikito** [comment]
Thanks for your kind words!

You are totally right. I have missed documenting these. In fact, I think a "reference" page describing all the default methods, not just the ones you mentioned, would be tremendously useful. I am a bit busy at the moment, but I will try to get it done when I get some prioritary things out of the way.

**Comment by kikito** [comment]
Hi there! I have created a new "reference page" describing the default methods. You can find it here:

https://github.com/kikito/middleclass/wiki/Reference

I hope it clarifies the questions you had regarding those undescribed methods. If not, feel free to reopen this issue and ask away! And if you think you can improve it, feel free to make changes too!

**Comment by Guard13007** [comment]
Thank you!

**Comment by MrStradivarius** [comment]
Thank you very much! That's awesome, and just what was needed. :)
