### ISSUE TITLE
Wiki doesn't say that you can create instances with __call

### ISSUE THREAD

**Issue by EliasD** [kikito/middleclass#40]
Using this library for the first time and so far I've found it absolutely wonderful. Great job :+1: 

I was pleasantly surprised when I've found out that this works:
```lua
local SomeClass = class("SomeClass")
local someObj = SomeClass()
```
I think that this must be documented, because I've found no mentions that you can do this stuff.
Any reason why ```SomeClass:new()``` is used everywhere other than missing mentions of this? Does ```SomeClass()``` have any drawbacks?

**Comment by kikito** [comment]
Hi there, thanks for your kind words!

Indeed, you can use `SomeClass()` without `new`. There are no drawbacks. I use `:new` everywhere in the wiki just to stay consistent (it is a bit more explicit, and it also helps people coming from other languages where new is needed).

I have updated the [reference page](https://github.com/kikito/middleclass/wiki/Reference) to include this. Thanks for pointing it out!

**Comment by EliasD** [comment]
Nice, thanks!

What's cool about calling ```SomeClass()``` is that if constructor takes one table arg, you can create objects with a pretty nice syntax:
```lua
local someVar = SomeClass { param1 = "hello", param2 = 5 }
```

**Comment by qaisjp** [comment]
Lua does that already:

```
function test(tab)
    print(tab.output)
end

test{output="hello world"}
-- > hello world 
```

**Comment by EliasD** [comment]
Yep, that's why I show how I use this feature :)

**Comment by qaisjp** [comment]
Oh right :D I misunderstood your comment
