### ISSUE TITLE
class.name doesn't work

### ISSUE THREAD

**Issue by Nathan1852** [kikito/middleclass#42]
I'm not sure if I'm doing something rong or if this actually is a problem.

When I create a class just like you do in the example (class:initialize()) then I only can access the name and super properties if I'm calling myClass.class.name or myClass.class.super. It doesn't work with myClass.name like in the example.

My code is something like this:
`
-- base class

local control = gui.class("base") -- gui.class is just middleclass

function control:initialize(parent)
    self.parent = parent
    -- self.name is nil here
end

return control

-- label class

local control =  gui.class("label", gui.controls.base)

function control:initialize(parent, text)
    gui.controls.base.initialize(self,parent)
    self.text = text
    -- self.name is also nil here
end

return control

-- main file
local screen = gui.controls.screen()
local label = gui.controls.label(screen,"Test Text")

-- label.name and label.super are both nil
-- label.class.name and label.class.super both work
`

**Comment by kikito** [comment]
That seems like the correct behaviour. What example are  you referring to? I might need to correct it.

**Comment by Nathan1852** [comment]
I'm refering to the reference page in the wiki.

It says that self.name would work.
It also says that self:isSubclassOf etc would work, which it probably wouldnt, since those methods are only available in self.class

**Comment by kikito** [comment]
`.name` works in a class. In general, that means something returned by `class(...)`. Not something returned by `:new`.

In the methods where you see `self.name`, notice that it says `static` in their declaration:

```
function MyClass.static:sublassed(other)
  print("Created a subclass of MyClass: " .. other.name)
end
```
In a `static` method, `self` is not an instance of the class, it is the class itself. In the non-static methods, `self` is an instance.

**Comment by Nathan1852** [comment]
Ah, so I misread the reference. Thanks for the quick answer
