### ISSUE TITLE
__newindex declaration makes it impossible to have public attributes

### ISSUE THREAD

**Issue by Kinrany** [kikito/middleclass#44]
If I declare `__newindex`, I can't create public attributes in `initialize` because `__newindex` is being called. Is this intentional?

```
class = 'middleclass.lua'

local MyClass = class('MyClass')

function MyClass:initialize(x)
    self.x = x
    --print("X = " .. self.x)                     --> error
end

local _table = {}

function MyClass:__newindex(key, value)
    _table[key] = value
    print("Key: " .. key .. "  Value: " .. value) 
end

local myInstance = MyClass:new(1)
myInstance.x = 2
print(myInstance.x)
```

Output:
```
Key: x Value: 1
Key: x Value: 2
nil
```

**Comment by mpeterv** [comment]
I think that's intentional. Like simple methods, metamethods are already working when `initialize` is called. You have to use `rawset` to bypass it.

**Comment by Kinrany** [comment]
Also it feels counterintuitive that `self.x` in `initialize` and `myInstance.x` behave differently.

**Comment by mpeterv** [comment]
What do you mean? They behave the same. Setting both triggers __newindex, accessing both returns nil.

**Comment by Kinrany** [comment]
The error is caused by trying to concat nil, my bad.

I guess everything works as intended, just not how I expected it to work.

**Comment by kikito** [comment]
Alright! Thank you for using middleclass! <3 <3
