### ISSUE TITLE
Defining an instance method "name"

### ISSUE THREAD

**Issue by kappe-c** [kikito/middleclass#47]
I just stumbled across the issue given in the title.
I knew from the documentation that for each class a static variable `name` is defined but I wouldn't have guessed (and find it quite restricting) that this affects the namesapce of instance methods. Don't `Class.sth` and `instance.sth` have different look-up chains?
Consider the following code sample.
```lua
local class = require 'middleclass'

local Foo = class 'Foo'
local foo = Foo()

print(Foo.name) --> Foo
assert(foo.class.name == Foo.name) -- secure fallback to get static class members
print(foo.name) --> nil

-- Foo.static.name = 'Bar' -- has no effect

function Foo:name() -- equivalent to function Foo.name(self)
	print('method "name" is called')
end

-- foo:name() -- attempt to call a nil value (method 'name')
print(Foo.name) --> function: 0x123456
print(foo.name) --> nil
```
Is this a bug, intended, unavoidable? What could be a workaround if one really wanted a `name` method? (I know that using `getName` would be one solution.)

**Comment by qaisjp** [comment]
foo is instantiated before you define Foo:name

Move line 4 after the method creation and try again

**Comment by kappe-c** [comment]
> foo is instantiated before you define Foo:name

I'm afraid that doesn't matter:
```lua
local class = require 'middleclass'

local Foo = class 'Foo'

function Foo:name() -- equivalent to function Foo.name(self)
	print('method "name" is called')
end

local foo = Foo()
foo:name() -- attempt to call a nil value (method 'name')
print(Foo.name) --> function: 0x123456
print(foo.name) --> nil (btw: that's an ordinary field that could have been set in the constructor)
```

**Comment by mpeterv** [comment]
`name`, `static`, and `subclasses` properties of a class (plus some private once starting with underscores) and `class` property of an instance are special, they don't live in normal namespaces.

**Comment by kikito** [comment]
Yep, @mpeterv is correct. There's another special property in subclasses: `super`.

When you create a class like so:

    local Foo = class('Foo')

The `name` attribute is automatically set for that class:

    assert(Foo.name == 'Foo')

Instances don't have this problem so you can use `instance.name` however you want (an instance method called `name` should work, but I am not 100% sure. Just name it something else if it gives you trouble).

I'm closing this down now, but reopen if you need more help.
