### ISSUE TITLE
Make it possible to include superclasses and mixins by string names

### ISSUE THREAD

**Issue by ichesnokov** [kikito/middleclass#57]
After using `middleclass` for some time I found myself out doing things like this:

```lua
local _M = require('middleclass')('State.Moving', require('State.Base'))
  :include(require('Mixin.Character'))
  :include(require('Mixin.Moving'))
```

It would be more convenient to be able to do it without constantly calling `require`, e.g.:

```lua
local _M = require('middleclass')('State.Moving', 'State.Base')
  :include('Mixin.Character')
  :include('Mixin.Moving')
```

It's something that e.g. Moose OO framework in Perl does with its `extends` and `with` keywords.

I also have read a discussion on the similar issue https://github.com/kikito/middleclass/issues/52, and I think that format of an argument (i.e., string with class name vs class variable) already provides sufficient explicitness, and if in doubt / having issues, it's easy to switch back to class variables instead of strings in some particular project.

**Comment by jojo59516** [comment]
Hi, I agree it looks more clear. And in fact you can easily wrap the `middleclass` as you want. 

For example:
```Lua
-- class.lua
local middleclass = require("middleclass")

return function (name, super)
    if type(super) == "string" then
        super = require(super)
    end
    return middleclass.class(name, super)
end
```
And then you can do
```Lua
-- Moving.lua
local _M = require('class')('State.Moving', 'State.Base')
    :include('Mixin.Character')
    :include('Mixin.Moving')
```
as you like.

For me, I always prefer a more pure, simple module.

**Comment by ichesnokov** [comment]
Thanks, @jojo59516, that looks quite reasonable.
